name: 'Validate metrics.json schema'

on:
  workflow_dispatch:
  push:
    paths:
      - 'metrics.json'
  pull_request:

jobs:
  test:
    name: 'Validate metrics.json schema'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Validate JSON Schema for metrics.json'
        shell: pwsh
        run: |
          $files = Get-ChildItem -Recurse | Where-Object { $_.Name -eq 'metrics.json' }

          $files |% {
            Write-Host "Found $($_.Fullname). Validate JSON Schema."
            ./.github/scripts/validateMetrics.ps1 -metricsFile $($_.FullName)
          }

      - name: Check Errors and Warnings
        run: |
          if [[ "${{ steps.run_tests.outputs.errors }}" == "true" ]]; then
            echo "Errors were found. Failing the workflow."
            exit 1
          fi

          if [[ "${{ steps.run_tests.outputs.warnings }}" == "true" ]]; then
            echo "Warnings were found. Failing the workflow."
            exit 1
          fi