name: 'Validate metrics.json schema'

on:
  workflow_dispatch:
  push:
    paths:
      - 'metrics.json'
  pull_request:

jobs:
  test:
    name: 'Validate metrics.json schema'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Validate JSON Schema for metrics.json'
        id: validation
        shell: pwsh
        run: |
          $files = Get-ChildItem -Recurse | Where-Object { $_.Name -eq 'metrics.json' }

          Write-Output "ERROR_COUNT=0" >> $env:GITHUB_ENV

          $files |% {
            Write-Host "Found $($_.Fullname). Validate JSON Schema."
            ./.github/scripts/validateMetrics.ps1 -metricsFile $($_.FullName)
          }

          Write-Host "$($env:ERROR_COUNT) errors found in JSON Schema validation."

          if ($env:ERROR_COUNT -gt 0) {
            Write-Error "Found $($env:ERROR_COUNT) errors in JSON Schema validation."
            exit 1
          }